services:
  nginx:
    # Testing: Use different port to avoid conflicts
    ports:
      - "8081:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db_test
      - DB_DATABASE=balance_flow_test
      - CACHE_DRIVER=array
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=array
    depends_on:
      - db_test

  db_test:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: balance_flow_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - balance-flow-network

  db:
    profiles:
      - donotstart
