services:
  nginx:
    # Testing: Use different port to avoid conflicts
    ports:
      - "8081:80"

  app:
    env_file:
      - .env.testing

  db:
    environment:
      POSTGRES_DB: balance_flow_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: !reset []
    tmpfs:
      - /var/lib/postgresql/data
