# For more information: https://laravel.com/docs/sail
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        image: balance-flow-app
        environment:
            APP_ENV: '${APP_ENV:-local}'
            APP_DEBUG: '${APP_DEBUG:-true}'
            DB_CONNECTION: '${DB_CONNECTION:-pgsql}'
            DB_HOST: '${DB_HOST:-pgsql}'
            DB_PORT: '${DB_PORT:-5432}'
            DB_DATABASE: '${DB_DATABASE:-balance_flow}'
            DB_USERNAME: '${DB_USERNAME:-sail}'
            DB_PASSWORD: '${DB_PASSWORD:-password}'
            REDIS_HOST: '${REDIS_HOST:-redis}'
            REDIS_PORT: '${REDIS_PORT:-6379}'
        volumes:
            - './storage:/var/www/app/storage'
            - './bootstrap/cache:/var/www/app/bootstrap/cache'
        networks:
            - default
        depends_on:
            - pgsql
            - redis
        healthcheck:
            test: ["CMD", "php-fpm", "-t"]
            interval: 30s
            timeout: 10s
            retries: 3

    nginx:
        image: nginx:alpine
        depends_on:
            - app
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './docker/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
            - './public:/var/www/app/public:ro'
            - './storage/app/public:/var/www/app/storage/app/public'
        networks:
            - default


    pgsql:
        image: 'postgres:17-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-password}'
            POSTGRES_DB: '${DB_DATABASE:-balance_flow}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'database:/var/lib/postgresql/data'
        networks:
            - default
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USERNAME:-sail}", "-d", "${DB_DATABASE:-balance_flow}"]
            retries: 5
            timeout: 5s

    redis:
        image: 'redis:7-alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'cache:/data'
        networks:
            - default
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 5
            timeout: 3s

networks:
    default:
        driver: bridge

volumes:
    database:
        external: true
        name: ${PROJECT_NAME:-balance-flow-be}_database
    cache:
        external: true
        name: ${PROJECT_NAME:-balance-flow-be}_cache
