# For more information: https://laravel.com/docs/sail
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        image: balance-flow-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './storage:/var/www/html/storage'
            - './bootstrap/cache:/var/www/html/bootstrap/cache'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis

    nginx:
        build:
            context: .
            dockerfile: Dockerfile
            target: nginx
        image: balance-flow-nginx
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './storage/app/public:/var/www/html/storage/app/public'
        networks:
            - sail
        depends_on:
            - app

    pgsql:
        image: 'postgres:17-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-password}'
            POSTGRES_DB: '${DB_DATABASE:-balance_flow}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'sailpgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USERNAME:-sail}"]
            retries: 5
            timeout: 5s

    redis:
        image: 'redis:7-alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 5
            timeout: 3s

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sailpgsql:
        driver: local
    sailredis:
        driver: local
